language: node_js
node_js:
 - "node"

cache: npm
script: npm run build

node_js:
  - 14

deploy:
  provider: surge
  login: allenclark@u.boisestate.edu
  token: $SURGE_TOKEN
  project: ./dist
  domain: theallenc.surge.sh
  cleanup: false
  on:
    branch: master
  edge: true # opt in to dpl v2
